services:
  drawdb:
    build: .
    image: drawdb
    container_name: drawdb
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DIAGRAM_STORE_PATH: /data/diagrams
    volumes:
      - drawdb-data:/data
    networks:
      - default

volumes:
  drawdb-data:

networks:
  default:
    driver: bridge
